#!/bin/bash
# Copyright (c) 2013, Google Inc. Please see the AUTHORS file for details.
# All rights reserved. Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

DART_VER=$(dart --version 2>&1)
if [[ "$DART_VER" != Dart\ VM\ version:* ]] ; then
  echo "Error: Unable to execute 'dart'"
  echo "       Please set the DART_SDK environment variable to the SDK path."
  echo "       And add DART_SDK/bin to PATH environment variable."
  echo "       e.g.: 'export DART_SDK=your/path/to/dart/dart-sdk'";
  echo "             'export PATH=\$PATH:\$DART_SDK/bin'";
  exit -1
fi

dart tool/grind.dart $@
